Update schema string in snyk.go (#521)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -211,26 +211,26 @@ jobs:
       run: 
           snyk code test --sarif --policy-path=.snyk  --sarif-file-output=snyk-code.json --prune-repeated-subdependencies
     
-    - name: Report Snyk Code to Kosli
-      if:  ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) &&  (success() || failure()) && inputs.report_results }}
-      env:
-        KOSLI_API_TOKEN: ${{ secrets.kosli_reporting_api_token }}
-      run: kosli attest snyk 
-           --name snyk-code-test 
-           --flow ${{ inputs.FLOW_NAME }}  
-           --trail ${{ inputs.TRAIL_NAME }} 
-           --scan-results  snyk-code.json
-           --org ${{ inputs.KOSLI_ORG }}
+    # - name: Report Snyk Code to Kosli
+    #   if:  ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) &&  (success() || failure()) && inputs.report_results }}
+    #   env:
+    #     KOSLI_API_TOKEN: ${{ secrets.kosli_reporting_api_token }}
+    #   run: kosli attest snyk 
+    #        --name snyk-code-test 
+    #        --flow ${{ inputs.FLOW_NAME }}  
+    #        --trail ${{ inputs.TRAIL_NAME }} 
+    #        --scan-results  snyk-code.json
+    #        --org ${{ inputs.KOSLI_ORG }}
     
-    - name: Slack Notification on Failure
-      if: ${{ failure() }}
-      uses: rtCamp/action-slack-notify@v2
-      env:
-        SLACK_CHANNEL: ${{ secrets.slack_channel }}
-        SLACK_COLOR: ${{ job.status }}
-        SLACK_TITLE: Snyk Code Failed in CLI repository
-        SLACK_USERNAME: GithubActions
-        SLACK_WEBHOOK: ${{ secrets.slack_webhook }}
+    # - name: Slack Notification on Failure
+    #   if: ${{ failure() }}
+    #   uses: rtCamp/action-slack-notify@v2
+    #   env:
+    #     SLACK_CHANNEL: ${{ secrets.slack_channel }}
+    #     SLACK_COLOR: ${{ job.status }}
+    #     SLACK_TITLE: Snyk Code Failed in CLI repository
+    #     SLACK_USERNAME: GithubActions
+    #     SLACK_WEBHOOK: ${{ secrets.slack_webhook }}
 
   snyk-dependency-test:
     if: ${{ inputs.run_snyk }}
@@ -258,23 +258,23 @@ jobs:
       run: 
           snyk test --sarif --policy-path=.snyk  --sarif-file-output=snyk-dependency.json --prune-repeated-subdependencies
     
-    - name: Report Snyk Test to Kosli
-      if:  ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) &&  (success() || failure()) && inputs.report_results }}
-      env:
-        KOSLI_API_TOKEN: ${{ secrets.kosli_reporting_api_token }}
-      run: kosli attest snyk 
-           --name snyk-dependency-test 
-           --flow ${{ inputs.FLOW_NAME }}  
-           --trail ${{ inputs.TRAIL_NAME }} 
-           --scan-results  snyk-dependency.json
-           --org ${{ inputs.KOSLI_ORG }}
+    # - name: Report Snyk Test to Kosli
+    #   if:  ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) &&  (success() || failure()) && inputs.report_results }}
+    #   env:
+    #     KOSLI_API_TOKEN: ${{ secrets.kosli_reporting_api_token }}
+    #   run: kosli attest snyk 
+    #        --name snyk-dependency-test 
+    #        --flow ${{ inputs.FLOW_NAME }}  
+    #        --trail ${{ inputs.TRAIL_NAME }} 
+    #        --scan-results  snyk-dependency.json
+    #        --org ${{ inputs.KOSLI_ORG }}
     
-    - name: Slack Notification on Failure
-      if: ${{ failure() }}
-      uses: rtCamp/action-slack-notify@v2
-      env:
-        SLACK_CHANNEL: ${{ secrets.slack_channel }}
-        SLACK_COLOR: ${{ job.status }}
-        SLACK_TITLE: Snyk Test Failed in CLI repository
-        SLACK_USERNAME: GithubActions
-        SLACK_WEBHOOK: ${{ secrets.slack_webhook }}
+    # - name: Slack Notification on Failure
+    #   if: ${{ failure() }}
+    #   uses: rtCamp/action-slack-notify@v2
+    #   env:
+    #     SLACK_CHANNEL: ${{ secrets.slack_channel }}
+    #     SLACK_COLOR: ${{ job.status }}
+    #     SLACK_TITLE: Snyk Test Failed in CLI repository
+    #     SLACK_USERNAME: GithubActions
+    #     SLACK_WEBHOOK: ${{ secrets.slack_webhook }}
